# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c161bfaf5e8f2fb82672cd2d4b99d5a34bdb4281dff0198f1a7ad3111a989cfe9b348f1fa74b9584cb00f1b31195e4a4968e78f0840c159e56dc834bd352d0b

test:
  secret_key_base: 231701e0be24dfbc29fa88dc692b46193acb6e3633e01f040cc20f1ed224a6f9d04423e9023cfc6ff2b790025f8b14737561105bd396702280b0150e18cec8b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
